- name: Install Java and Apache
  hosts: all
  become: yes

  tasks:
    - name: update_cache
      apt:
        update_cache: yes
        
    - name: Install Apache
      apt:
        name: apache2
        state: present  