- name: Install Java and Apache
  hosts: all
  become: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
    - name : update update_cache
      apt: 
      update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

  