- name: Ping test
  hosts: all
  gather_facts: yes

  tasks:
    - name: Test connectivity
      ansible.builtin.ping:
    - name: Identify Jenkins user
      command: whoami
      delegate_to: localhost
      register: whoami_result

    - name: Show Jenkins user
      debug:
        msg: "Playbook executed by {{ whoami_result.stdout }}"

