
- name: Ping test
  hosts: all
  gather_facts: yes

  tasks:
    - name: Test connectivity
      ansible.builtin.ping:
    - name: Show user running playbook
      debug:
        msg: "Playbook is running as user {{ jenkins_user }}"
