- name: Install Terraform manually on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Ensure required packages are installed
      apt:
        update_cache: yes

    - name: Download Terraform binary
      get_url:
        url: https://releases.hashicorp.com/terraform/1.15.9/terraform_1.15.9_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /tmp/
        remote_src: yes
        
    - name: Move Terraform binary to /usr/local/bin
      copy:
        src: /tmp/terraform
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: yes
        
    - name: Verify Terraform installation
      command: terraform -v
      register: terraform_version_output

    - name: Show installed Terraform version
      debug:
        msg: "Installed Terraform version: {{ terraform_version_output.stdout }}"