- name: installation of apache
  hosts: all
  become: yes
  tasks:
    - name: update cache in ubuntu
      apt:
        update_cache: yes
    - name: install webserver
      apt:
        name: apache2
        state: present
